### ISSUE TITLE
Chat bubbles

### ISSUE THREAD

**Issue by citizenrich** [rapidpro/chatpro#12]
Use chat bubbles to display conversations or indent or otherwise add a visual cue when messages are coming from the dashboard user versus from other contacts/users.

**Comment by rowanseymour** [comment]
This for the sender names on the list of messages right? I think we could that by using different background colors. I'd prefer that to re-using the icons on the room details panel.

**Comment by rowanseymour** [comment]
I've added some colour differentiation for user vs contact. Feedback welcome.
