### ISSUE TITLE
Is this still a going concern?

### ISSUE THREAD

**Issue by cromulus** [rapidpro/chatpro#17]
Setting up our own instance of the whole RapidPro toolkit and having a chat-like interface would be fantastic, I'm just concerned that it doesn't look like this has been touched in three years.

Thanks!

**Comment by rowanseymour** [comment]
Yeah this project is no longer maintained and would take a bit of work to get running against latest API etc

**Comment by cromulus** [comment]
Thanks for the update. might be a good idea to update the readme. 

Is there an alternative for real time chat with rapidpro contacts? Would be ready, especially when someone gets confused in a flow to be able to triage them to a human. 

Thanks again!

**Comment by rowanseymour** [comment]
This project was more about group chats - allowing orgs to maintain multiple "chat rooms" and delegate responsibility for managing those groups to users who don't necessarily have access to the main rapidpro account.

We don't really have a good mechanism for exiting people out of flows and transferring them to a human, but it would be neat.

**Comment by cromulus** [comment]
Got it. Agreed, would be neat. 

I was thinking about some sort of slack integration so if someone said "human" or somesuch, I had a flow that just looped with the option for the slack operator to send a command that would break the loop and send the person back into the flow.
