### ISSUE TITLE
Delete contact within RapidPro/TextIt contact manager doesn't remove contact in chatpro

### ISSUE THREAD

**Issue by citizenrich** [rapidpro/chatpro#7]
When a contact is deleted in the RapidPro/TextIt contact management page the change will not be reflected in ChatPro. Only flow-based deletions appear to be properly reflected.

**Comment by rowanseymour** [comment]
We don't currently have any good way to hook into non-flow contact changes in RapidPro and push them to ChatPro. The solution we came up with was to have ChatPro fetch all contacts from RapidPro on a regular schedule (currently every hour) and sync that list against it's own list. Doesn't seem like that is working correctly on the staging server. Will investigate.

**Comment by citizenrich** [comment]
With the shorter syncing time this should be fixed.
