### ISSUE TITLE
Move language selection buttons

### ISSUE THREAD

**Issue by citizenrich** [rapidpro/chatpro#8]
Suggest moving the buttons for selecting interface languages to the top of the page and consolidate into one dropdown menu

**Comment by rowanseymour** [comment]
I'm not sure about this. There's not much room up top, and in TracPro (assuming we want these dashboards to be consistent) there's even less room. Language selection will usually be a infrequently used function that users set from their first login page and leave.

**Comment by citizenrich** [comment]
Agreed. Time to close this one out.
